export const userConstants = {
    LOGIN_REQUEST : 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS : 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE : 'USERS_LOGIN_FAILURE',
    LOGOUT : 'LOGOUT'
}


export const searchConstants = {
    SEARCH_REQUEST : 'SEARCH_REQUEST',
    SEARCH_SUCCESS : 'SEARCH_SUCCESS',
    SEARCH_FAILURE : 'SEARCH_FAILURE',
    PLANET_SELECT  : 'PLANET_SELECT',
};